-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."client_status" AS ENUM('prospect', 'active', 'on_hold', 'completed', 'archived');--> statement-breakpoint
CREATE TABLE "clients" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid DEFAULT auth.uid() NOT NULL,
	"name" text NOT NULL,
	"status" "client_status" DEFAULT 'prospect' NOT NULL,
	"industry" text,
	"website" text,
	"location" text,
	"account_owner" text,
	"primary_contact_name" text,
	"primary_contact_email" text,
	"notes" text,
	"segment" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "clients_name_check" CHECK ((char_length(name) >= 1) AND (char_length(name) <= 200))
);
--> statement-breakpoint
ALTER TABLE "clients" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "projects" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"project_name" text
);
--> statement-breakpoint
ALTER TABLE "projects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "clients_owner_id_idx" ON "clients" USING btree ("owner_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "clients_owner_status_idx" ON "clients" USING btree ("owner_id" uuid_ops,"status" uuid_ops);--> statement-breakpoint
CREATE POLICY "Users can delete their own clients" ON "clients" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((( SELECT auth.uid() AS uid) = owner_id));--> statement-breakpoint
CREATE POLICY "Users can update their own clients" ON "clients" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can create their own clients" ON "clients" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can read their own clients" ON "clients" AS PERMISSIVE FOR SELECT TO "authenticated";
*/