// Generated by `pnpm db:types`. Do not edit by hand.
// Hand-seeded to match supabase/migrations until the project is linked;
// regenerate once the database is live.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      clients: {
        Row: {
          account_owner: string | null;
          created_at: string;
          id: string;
          industry: string | null;
          location: string | null;
          name: string;
          notes: string | null;
          owner_id: string;
          primary_contact_email: string | null;
          primary_contact_name: string | null;
          segment: string | null;
          status: Database["public"]["Enums"]["client_status"];
          updated_at: string;
          website: string | null;
        };
        Insert: {
          account_owner?: string | null;
          created_at?: string;
          id?: string;
          industry?: string | null;
          location?: string | null;
          name: string;
          notes?: string | null;
          owner_id?: string;
          primary_contact_email?: string | null;
          primary_contact_name?: string | null;
          segment?: string | null;
          status?: Database["public"]["Enums"]["client_status"];
          updated_at?: string;
          website?: string | null;
        };
        Update: {
          account_owner?: string | null;
          created_at?: string;
          id?: string;
          industry?: string | null;
          location?: string | null;
          name?: string;
          notes?: string | null;
          owner_id?: string;
          primary_contact_email?: string | null;
          primary_contact_name?: string | null;
          segment?: string | null;
          status?: Database["public"]["Enums"]["client_status"];
          updated_at?: string;
          website?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      client_status:
        | "prospect"
        | "active"
        | "on_hold"
        | "completed"
        | "archived";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database["public"];

export type Tables<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> =
  PublicSchema["Enums"][T];
